//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0629_MVC小專.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignBill
    {
        public int billID { get; set; }
        public string company { get; set; }
        public string adate { get; set; }
        public string product { get; set; }
        public string standards { get; set; }
        public Nullable<int> timehour { get; set; }
        public Nullable<int> overtime { get; set; }
        public Nullable<int> freight { get; set; }
        public Nullable<int> expenses { get; set; }
        public string customer { get; set; }
        public string driver { get; set; }
        public Nullable<int> number { get; set; }
        public string bill_userID { get; set; }
    }
}
